### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by crusaderky** [coiled/benchmarks#650]
The following are blockers to enable Python 3.11 in the coiled-runtime recipe:

### Must have
- [x] Bump dask to >=2022.12.1
- [x] Bump tornado to >=6.2
- [x] Wait for numba release https://github.com/numba/numba/issues/8304
- [x] Wait for numba to land in conda-forge https://github.com/conda-forge/numba-feedstock/pull/115
- [x] Update coiled-runtime CI to test 3.11 #858

### Should have
- [ ] Add Python 3.11 to dask-ml CI; potentially fix bugs and push a new release accordingly https://github.com/dask/dask-ml/issues/970
- [ ] Go through the changelog of all third-party dependencies and spot Python 3.11-related bugfixes. Bump pinned versions as needed.
- [x] #552 

zict officially supports Python 3.11 since 2.3.0 (not yet released), but 2.2.0 works just fine with it.

**Comment by crusaderky** [comment]
CC @jrbourbeau @ncclementi

**Comment by ncclementi** [comment]
Once the numba realease is out, we can start testing CI on `latest` until we do have a newer runtime release. 
We can bump the needed and wanted packages in the recipe in main, and modify CI to test the py3.11 on latests. But I think we are mostly blocked by numba's release.

**Comment by shughes-uk** [comment]
Watching this as it'll be our sign to support 3.11 more thoroughly on platform

**Comment by crusaderky** [comment]
numba for Python 3.11 is now in conda-forge.
This issue is now blocked by https://github.com/coiled/benchmarks/pull/793
